using System;
using System.Linq;
using Shoko.Plugin.Abstractions.Enums;

#nullable enable
namespace Shoko.Plugin.Abstractions.Extensions;

public static class LanguageExtensions
{
    public static TextLanguage ToTextLanguage(this string lang)
    {
        return lang.ToUpper() switch
        {
            "EN" or "ENG" => TextLanguage.English,
            "X-JAT" => TextLanguage.Romaji,
            "JA" or "JPN" => TextLanguage.Japanese,
            "AR" or "ARA" => TextLanguage.Arabic,
            "BD" or "BAN" => TextLanguage.Bangladeshi,
            "BG" or "BUL" => TextLanguage.Bulgarian,
            "CA" => TextLanguage.FrenchCanadian,
            "CS" or "CES" or "CZ" => TextLanguage.Czech,
            "DA" or "DAN" or "DK" => TextLanguage.Danish,
            "DE" or "DEU" => TextLanguage.German,
            "EL" or "ELL" or "GR" => TextLanguage.Greek,
            "ES" or "SPA" => TextLanguage.Spanish,
            "ET" or "EST" => TextLanguage.Estonian,
            "FI" or "FIN" => TextLanguage.Finnish,
            "FR" or "FRA" or "CA" => TextLanguage.French,
            "GL" or "GLG" => TextLanguage.Galician,
            "HE" or "HEB" or "IL" => TextLanguage.Hebrew,
            "HU" or "HUN" => TextLanguage.Hungarian,
            "IT" or "ITA" => TextLanguage.Italian,
            "KO" or "KOR" => TextLanguage.Korean,
            "LT" or "LIT" => TextLanguage.Lithuanian,
            "MN" or "MON" => TextLanguage.Mongolian,
            "MS" or "MSA" or "MY" => TextLanguage.Malaysian,
            "NL" or "NLD" => TextLanguage.Dutch,
            "NO" or "NOR" => TextLanguage.Norwegian,
            "PL" or "POL" => TextLanguage.Polish,
            "PT" or "POR" => TextLanguage.Portuguese,
            "PT-BR" => TextLanguage.BrazilianPortuguese,
            "RO" or "RON" => TextLanguage.Romanian,
            "RU" or "RUS" => TextLanguage.Russian,
            "SK" or "SLK" => TextLanguage.Slovak,
            "SL" or "SLV" => TextLanguage.Slovenian,
            "SR" or "SRP" => TextLanguage.Serbian,
            "SV" or "SWE" or "SE" => TextLanguage.Swedish,
            "TH" or "THA" => TextLanguage.Thai,
            "TR" or "TUR" => TextLanguage.Turkish,
            "UK" or "UKR" or "UA" => TextLanguage.Ukrainian,
            "VI" or "VIE" => TextLanguage.Vietnamese,
            "ZH" or "ZHO" => TextLanguage.Chinese,
            "X-ZHT" => TextLanguage.Pinyin,
            "ZH-HANS" => TextLanguage.ChineseSimplified,
            "ZH-HANT" => TextLanguage.ChineseTraditional,
            "AF" or "AFR" => TextLanguage.Afrikaans,
            "SQ" or "SQI" => TextLanguage.Albanian,
            "AM" or "AMH" => TextLanguage.Amharic,
            "HY" or "HYE" => TextLanguage.Armenian,
            "AZ" or "AZE" => TextLanguage.Azerbaijani,
            "EU" or "EUS" => TextLanguage.Basque,
            "BE" or "BEL" => TextLanguage.Belarusian,
            "BN" or "BEN" => TextLanguage.Bengali,
            "BS" or "BOS" => TextLanguage.Bosnian,
            "CA" or "CAT" => TextLanguage.Catalan,
            "NY" or "NYA" => TextLanguage.Chichewa,
            "CO" or "COS" => TextLanguage.Corsican,
            "HR" or "HRV" => TextLanguage.Croatian,
            "DV" or "DIV" => TextLanguage.Divehi,
            "EO" or "EPO" => TextLanguage.Esperanto,
            "FJ" or "FIJ" => TextLanguage.Fijian,
            "KA" or "KAT" => TextLanguage.Georgian,
            "GU" or "GUJ" => TextLanguage.Gujarati,
            "HT" or "HAT" => TextLanguage.HaitianCreole,
            "HA" or "HAU" => TextLanguage.Hausa,
            "IS" or "ISL" => TextLanguage.Icelandic,
            "IG" or "IBO" => TextLanguage.Igbo,
            "ID" or "IND" => TextLanguage.Indonesian,
            "GA" or "GLE" => TextLanguage.Irish,
            "JV" or "JAV" => TextLanguage.Javanese,
            "KN" or "KAN" => TextLanguage.Kannada,
            "KK" or "KAZ" => TextLanguage.Kazakh,
            "KM" or "KHM" => TextLanguage.Khmer,
            "KU" or "KUR" => TextLanguage.Kurdish,
            "KY" or "KIR" => TextLanguage.Kyrgyz,
            "LO" or "LAO" => TextLanguage.Lao,
            "LA" or "LAT" => TextLanguage.Latin,
            "LV" or "LAV" => TextLanguage.Latvian,
            "LB" or "LUX" => TextLanguage.Luxembourgish,
            "MK" or "MKD" => TextLanguage.Macedonian,
            "MG" or "MLG" => TextLanguage.Malagasy,
            "ML" or "MAL" => TextLanguage.Malayalam,
            "MT" or "MLT" => TextLanguage.Maltese,
            "MI" or "MRI" => TextLanguage.Maori,
            "MR" or "MAR" => TextLanguage.Marathi,
            "MY" or "MYA" => TextLanguage.MyanmarBurmese,
            "NE" or "NEP" => TextLanguage.Nepali,
            "OR" or "ORI" => TextLanguage.Oriya,
            "PS" or "PUS" => TextLanguage.Pashto,
            "FA" or "FAS" => TextLanguage.Persian,
            "PA" or "PAN" => TextLanguage.Punjabi,
            "QU" or "QUE" => TextLanguage.Quechua,
            "SM" or "SMO" => TextLanguage.Samoan,
            "GD" or "GLA" => TextLanguage.ScotsGaelic,
            "ST" or "SOT" => TextLanguage.Sesotho,
            "SN" or "SNA" => TextLanguage.Shona,
            "SD" or "SND" => TextLanguage.Sindhi,
            "SI" or "SIN" => TextLanguage.Sinhala,
            "SO" or "SOM" => TextLanguage.Somali,
            "SW" or "SWA" => TextLanguage.Swahili,
            "TG" or "TGK" => TextLanguage.Tajik,
            "TA" or "TAM" => TextLanguage.Tamil,
            "TT" or "TAT" => TextLanguage.Tatar,
            "TE" or "TEL" => TextLanguage.Telugu,
            "TK" or "TUK" => TextLanguage.Turkmen,
            "UG" or "UIG" => TextLanguage.Uighur,
            "UZ" or "UZB" => TextLanguage.Uzbek,
            "CY" or "CYM" => TextLanguage.Welsh,
            "XH" or "XHO" => TextLanguage.Xhosa,
            "YI" or "YID" => TextLanguage.Yiddish,
            "YO" or "YOR" => TextLanguage.Yoruba,
            "ZU" or "ZUL" => TextLanguage.Zulu,
            _ => TextLanguage.Unknown,
        };
    }
    
    public static string GetDescription(this TextLanguage lang)
    {
        return lang switch
        {
            TextLanguage.Romaji => "Japanese (romanji/x-jat)",
            TextLanguage.Japanese => "Japanese (kanji)",
            TextLanguage.Bangladeshi => "Bangladesh",
            TextLanguage.FrenchCanadian => "Canadian-French",
            TextLanguage.BrazilianPortuguese => "Brazilian Portuguese",
            TextLanguage.Chinese => "Chinese (any)",
            TextLanguage.ChineseSimplified => "Chinese (simplified)",
            TextLanguage.ChineseTraditional => "Chinese (traditional)",
            TextLanguage.Pinyin => "Chinese (pinyin/x-zhn)",
            _ => lang.ToString(),
        };
    }

    public static string ToLanguageCode(this TextLanguage lang)
    {
        return lang switch
        {
            TextLanguage.English => "en",
            TextLanguage.Romaji => "x-jat",
            TextLanguage.Japanese => "ja",
            TextLanguage.Arabic => "ar",
            TextLanguage.Bangladeshi => "bd",
            TextLanguage.Bulgarian => "bg",
            TextLanguage.FrenchCanadian => "ca",
            TextLanguage.Czech => "cz",
            TextLanguage.Danish => "da",
            TextLanguage.German => "de",
            TextLanguage.Greek => "gr",
            TextLanguage.Spanish => "es",
            TextLanguage.Estonian => "et",
            TextLanguage.Finnish => "fi",
            TextLanguage.French => "fr",
            TextLanguage.Galician => "gl",
            TextLanguage.Hebrew => "he",
            TextLanguage.Hungarian => "hu",
            TextLanguage.Italian => "it",
            TextLanguage.Korean => "ko",
            TextLanguage.Lithuanian => "lt",
            TextLanguage.Mongolian => "mn",
            TextLanguage.Malaysian => "ms",
            TextLanguage.Dutch => "ml",
            TextLanguage.Norwegian => "no",
            TextLanguage.Polish => "pl",
            TextLanguage.Portuguese => "pt",
            TextLanguage.BrazilianPortuguese => "pt-br",
            TextLanguage.Romanian => "ro",
            TextLanguage.Russian => "ru",
            TextLanguage.Slovak => "sk",
            TextLanguage.Slovenian => "sl",
            TextLanguage.Serbian => "sr",
            TextLanguage.Swedish => "sv",
            TextLanguage.Thai => "th",
            TextLanguage.Turkish => "tr",
            TextLanguage.Ukrainian => "uk",
            TextLanguage.Vietnamese => "vi",
            TextLanguage.Chinese => "zh",
            TextLanguage.Pinyin => "x-zht",
            TextLanguage.ChineseSimplified => "zh-hans",
            TextLanguage.ChineseTraditional => "zh-hant",
            TextLanguage.Afrikaans => "af",
            TextLanguage.Albanian => "sq",
            TextLanguage.Amharic => "am",
            TextLanguage.Armenian => "hy",
            TextLanguage.Azerbaijani => "az",
            TextLanguage.Basque => "eu",
            TextLanguage.Belarusian => "be",
            TextLanguage.Bengali => "bn",
            TextLanguage.Bosnian => "bs",
            TextLanguage.Catalan => "ca",
            TextLanguage.Chichewa => "ny",
            TextLanguage.Corsican => "co",
            TextLanguage.Croatian => "hr",
            TextLanguage.Divehi => "dv",
            TextLanguage.Esperanto => "eo",
            TextLanguage.Fijian => "fj",
            TextLanguage.Georgian => "ka",
            TextLanguage.Gujarati => "gu",
            TextLanguage.HaitianCreole => "ht",
            TextLanguage.Hausa => "ha",
            TextLanguage.Icelandic => "is",
            TextLanguage.Igbo => "ig",
            TextLanguage.Indonesian => "id",
            TextLanguage.Irish => "ga",
            TextLanguage.Javanese => "jv",
            TextLanguage.Kannada => "kn",
            TextLanguage.Kazakh => "kk",
            TextLanguage.Khmer => "km",
            TextLanguage.Kurdish => "ku",
            TextLanguage.Kyrgyz => "ky",
            TextLanguage.Lao => "lo",
            TextLanguage.Latin => "la",
            TextLanguage.Latvian => "lv",
            TextLanguage.Luxembourgish => "lb",
            TextLanguage.Macedonian => "mk",
            TextLanguage.Malagasy => "mg",
            TextLanguage.Malayalam => "ml",
            TextLanguage.Maltese => "mt",
            TextLanguage.Maori => "mi",
            TextLanguage.Marathi => "mr",
            TextLanguage.MyanmarBurmese => "my",
            TextLanguage.Nepali => "ne",
            TextLanguage.Oriya => "or",
            TextLanguage.Pashto => "ps",
            TextLanguage.Persian => "fa",
            TextLanguage.Punjabi => "pa",
            TextLanguage.Quechua => "qu",
            TextLanguage.Samoan => "sm",
            TextLanguage.ScotsGaelic => "gd",
            TextLanguage.Sesotho => "st",
            TextLanguage.Shona => "sn",
            TextLanguage.Sindhi => "sd",
            TextLanguage.Sinhala => "si",
            TextLanguage.Somali => "so",
            TextLanguage.Swahili => "sw",
            TextLanguage.Tajik => "tg",
            TextLanguage.Tamil => "ta",
            TextLanguage.Tatar => "tt",
            TextLanguage.Telugu => "te",
            TextLanguage.Turkmen => "tk",
            TextLanguage.Uighur => "ug",
            TextLanguage.Uzbek => "uz",
            TextLanguage.Welsh => "cy",
            TextLanguage.Xhosa => "xh",
            TextLanguage.Yiddish => "yi",
            TextLanguage.Yoruba => "yo",
            TextLanguage.Zulu => "zu",
            _ => "und",
        };
    }
    
    public static string GetString(this TitleType type)
    {
        return type.ToString().ToLowerInvariant();
    }

    public static TitleType GetTitleType(this string name)
    {
        foreach (var type in Enum.GetValues(typeof(TitleType)).Cast<TitleType>())
        {
            if (type.GetString().Equals(name.ToLowerInvariant())) return type;
        }

        return name.ToLowerInvariant() switch
        {
            "syn" => TitleType.Synonym,
            "card" => TitleType.TitleCard,
            "kana" => TitleType.KanjiReading,
            "kanareading" => TitleType.KanjiReading,
            _ => TitleType.None,
        };
    }
}
